### PR TITLE
Fix for Issue #4

### LINKED ISSUE #4: Decoded byte[] is shorter than input byte[] with leading 0-bytes
The actual problem is this: if the encoded byte[] has leading null-bytes (zero), then these are cut off by this algorithm. So the resulting byte[] is shorter than the input!

In this implementation this is masked by the fact that only the methods using strings as input are public (and strings don't normally contain the 0-byte)

### PR DESCRIPTION
**Pull request by DJGosnell**
Addresses #4 issue with byte arrays which start with 0.  The following items are changed:
 - Base62Converter.BaseConvert() is now public.
 - Base62Converter.BaseConvert() now will prepend zero bytes to the beginning of the returned byte array.

### CODE REVIEW

File: Base62/Base62Converter.cs [hunk 1]
```diff
@@ -86,15 +87,46 @@ public byte[] Decode(byte[] value)
...
+        /// </summary>
+        /// <param name="source">Byte array to convert.</param>
+        /// <param name="sourceBase">Source base to convert from.</param>
+        /// <param name="targetBase">Target base to convert to.</param>
+        /// <returns>Converted byte array.</returns>
+        public static byte[] BaseConvert(byte[] source, int sourceBase, int targetBase)
         {
-            var result = new List<int>();
+            if (targetBase < 0 || targetBase > 256)
+                throw new ArgumentOutOfRangeException(nameof(targetBase), targetBase, "Value must be between 0 & 257");
```
Comment (ghost1face) [inline Base62/Base62Converter.cs]:
```suggestion
                throw new ArgumentOutOfRangeException(nameof(targetBase), targetBase, "Value must be between 0 & 256");
```

File: Base62/Base62Converter.cs [hunk 2]
```diff
@@ -86,15 +87,46 @@ public byte[] Decode(byte[] value)
...
+            
+            if (sourceBase < 0 || sourceBase > 256)
+                throw new ArgumentOutOfRangeException(nameof(sourceBase), sourceBase, "Value must be between 0 & 257");
```
Comment (ghost1face) [inline Base62/Base62Converter.cs]:
```suggestion
                throw new ArgumentOutOfRangeException(nameof(sourceBase), sourceBase, "Value must be between 0 & 256");
```

File: Base62/Base62Converter.cs [hunk 3]
```diff
@@ -86,15 +87,46 @@ public byte[] Decode(byte[] value)
...
 
-        private static byte[] BaseConvert(byte[] source, int sourceBase, int targetBase)
+        /// <summary>
+        /// Converts source byte array from the source base to the destination base.
+        /// </summary>
+        /// <param name="source">Byte array to convert.</param>
+        /// <param name="sourceBase">Source base to convert from.</param>
+        /// <param name="targetBase">Target base to convert to.</param>
+        /// <returns>Converted byte array.</returns>
+        public static byte[] BaseConvert(byte[] source, int sourceBase, int targetBase)
```
Comment (ghost1face) [inline Base62/Base62Converter.cs]: Considering this is only for Base62 and not others, I'd rather keep this `private`.  For the sake of unit tests we can make `internal` and expose the internals to the test project

File: Base62/Base62Converter.cs [hunk 4]
```diff
@@ -86,15 +87,46 @@ public byte[] Decode(byte[] value)
...
+                result.Add(0);
+                initialStartOffset++;
+            }
+
+            int startOffset = initialStartOffset;
+
             while ((count = source.Length) > 0)
             {
-                var quotient = new List<byte>();
+                quotient.Clear();
```
Comment (ghost1face) [inline Base62/Base62Converter.cs:127]: 👍🏾

**Review by ghost1face — CHANGES_REQUESTED** [review]
Thanks for taking the time to contribute!  I've got a few notes I added below

File: Base62/Base62Converter.cs (hunk 1 above)
Comment (DJGosnell) [reply Base62/Base62Converter.cs]: I was thinking about the confusion between exclusive and inclusive here but I failed to write an accurate enough exception text.  What about this: ```Value must be between 1 & 256 (inclusive)```

Comment (ghost1face) [reply Base62/Base62Converter.cs]: I like that better, let's go that route

**Comment by ghost1face** [comment]
I'll have to get these actions working again, all tests pass

File: Base62/Base62Converter.cs (hunk 3 above)
Comment (DJGosnell) [reply Base62/Base62Converter.cs]: Understand this concern as it exposes additional required test coverage.  Can we make it `protected internal` at least as I would like to be able to call this method from a derived class.  I have a workflow which looks like this. `Base64 String -> byte[] -> Base62 String`.
If I lose the access to this method, then I have to `Base64 String -> byte[] -> UTF8 Encode String -> UTF8 Decode String -> Base62 String` which just adds extra work in some hot paths I have.

Comment (DJGosnell) [reply Base62/Base62Converter.cs]: I take this back.  I was thinking about an old workflow.  I will change it to internal only.  I'll expose the internal method to the test project.

**Review by ghost1face — APPROVED** [review]

**Comment by ghost1face** [comment]
Thanks for the update, I'll get this in after some cleanup on my end
